#!/bin/bash
if [ -z ${JENKINS_CLI_CONFIG} ]; then
  file="./cli.properties"
else
  file=$JENKINS_CLI_CONFIG
fi

if [ -f "$file" ]
then
  echo "Using cli.properties file..."

  while IFS='=' read -r key value
  do
    eval "${key}='${value}'"
  done < "$file"

  echo "User       = " $user
  echo "Token      = " $token
  echo "URL        = " $url
  echo ""
else
  echo "Configuration file [$file] not found."
  exit 1
fi

if [ ! -f jenkins-cli.jar ]; then
  wget $url/jnlpJars/jenkins-cli.jar
fi
java -jar jenkins-cli.jar -noKeyAuth -auth $user:$token -s $url/ "$@" | python -m json.tool
